/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.HocSinhController;
import Controller.HocPhiController;
import Controller.LopHocController;
import Model.HocSinh;
import Model.LopHoc;
import Model.HocPhi;
import Utils.Validation;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class QLHocPhiView extends javax.swing.JFrame {

    private HocPhi hocphi;
    private LopHoc lop;
    private HocSinh hosinh;
    LopHocController lopHocController;
    HocSinhController hocSinhController;
    HocPhiController hocPhiController;
    DefaultTableModel defaultTableModel;

    /**
     * Creates new form QLHocPhiView
     */
    public QLHocPhiView() {
        initComponents();

        ImageIcon image = new ImageIcon("C:\\Users\\Administrator\\Documents\\NetBeansProjects\\DemoBTL - Copy2\\src\\img\\logo.png");
        this.setIconImage(image.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        PopupMenu = new javax.swing.JPopupMenu();
        HienThi = new javax.swing.JMenuItem();
        PopupMenu2 = new javax.swing.JPopupMenu();
        Show = new javax.swing.JMenuItem();
        jPanel7 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        btn_Home = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        tab_thu = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_searchClass = new javax.swing.JButton();
        txt_search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Data_HocSinh_Lop = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_Data_HocPhiByLop1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btn_searchHS = new javax.swing.JButton();
        txt_search1 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_tenHS = new javax.swing.JTextField();
        txt_tenLop2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_Giatien2 = new javax.swing.JTextField();
        txt_Phainop2 = new javax.swing.JTextField();
        txt_Conthieu = new javax.swing.JTextField();
        txt_Danop = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_Nguoinop = new javax.swing.JTextField();
        btn_Submit = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txt_MaHV = new javax.swing.JTextField();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_Data_NopTien = new javax.swing.JTable();

        HienThi.setText("Hiển Thị");
        HienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HienThiActionPerformed(evt);
            }
        });
        PopupMenu.add(HienThi);

        Show.setText("Show");
        Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowActionPerformed(evt);
            }
        });
        PopupMenu2.add(Show);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1160, 509));

        jPanel7.setBackground(new java.awt.Color(153, 153, 255));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel28.setText("QUẢN LÝ HỌC PHÍ");

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-sakura-48.png"))); // NOI18N

        jLabel30.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel30.setText("Trường THCS Chuyên Phan Bội Châu______________ ");

        btn_Home.setBackground(new java.awt.Color(153, 153, 255));
        btn_Home.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-home-32.png"))); // NOI18N
        btn_Home.setMaximumSize(new java.awt.Dimension(89, 39));
        btn_Home.setMinimumSize(new java.awt.Dimension(89, 39));
        btn_Home.setPreferredSize(new java.awt.Dimension(89, 39));
        btn_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel29)
                .addGap(22, 22, 22)
                .addComponent(jLabel30)
                .addGap(118, 118, 118)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel29)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        tab_thu.setBackground(new java.awt.Color(204, 204, 255));
        tab_thu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_thuMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-book-shelf-96.png"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(204, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TÌM KIẾM LỚP HỌC ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N

        btn_searchClass.setBackground(new java.awt.Color(102, 255, 204));
        btn_searchClass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_searchClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-search-30.png"))); // NOI18N
        btn_searchClass.setText("Search");
        btn_searchClass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_searchClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchClassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_searchClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_searchClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_search))
                .addGap(99, 99, 99))
        );

        table_Data_HocSinh_Lop.setBackground(new java.awt.Color(204, 153, 255));
        table_Data_HocSinh_Lop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_Data_HocSinh_Lop);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-book-shelf-96.png"))); // NOI18N

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-book-shelf-96.png"))); // NOI18N

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-book-shelf-96.png"))); // NOI18N

        table_Data_HocPhiByLop1.setBackground(new java.awt.Color(204, 153, 255));
        table_Data_HocPhiByLop1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(table_Data_HocPhiByLop1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel25)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel27))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel27)
                            .addComponent(jLabel1)
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(15, Short.MAX_VALUE))))
        );

        tab_thu.addTab("Thống kê", jPanel2);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel5.setBackground(new java.awt.Color(204, 153, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TÌM KIẾM HỌC SINH", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N

        btn_searchHS.setBackground(new java.awt.Color(102, 255, 204));
        btn_searchHS.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_searchHS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-search-30.png"))); // NOI18N
        btn_searchHS.setText("Search");
        btn_searchHS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_searchHS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchHSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_search1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_searchHS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_searchHS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_search1))
                .addGap(99, 99, 99))
        );

        jPanel6.setBackground(new java.awt.Color(204, 153, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))), "THÔNG TIN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Tên học sinh");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Tên lớp");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Ngày nộp");

        txt_tenHS.setEditable(false);

        txt_tenLop2.setEditable(false);
        txt_tenLop2.setMinimumSize(new java.awt.Dimension(7, 15));
        txt_tenLop2.setPreferredSize(new java.awt.Dimension(7, 15));
        txt_tenLop2.setRequestFocusEnabled(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Giá tiền");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Phải nộp");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Đã nộp");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Còn thiếu/thừa");

        txt_Giatien2.setEditable(false);

        txt_Phainop2.setEditable(false);

        txt_Conthieu.setEditable(false);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Người nộp");

        txt_Nguoinop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NguoinopActionPerformed(evt);
            }
        });

        btn_Submit.setBackground(new java.awt.Color(102, 255, 204));
        btn_Submit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-touch-24.png"))); // NOI18N
        btn_Submit.setText("Submit");
        btn_Submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SubmitActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Mã HV");

        txt_MaHV.setEditable(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Submit)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Giatien2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Phainop2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tenLop2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tenHS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabel20))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel16))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel17)))
                                .addGap(13, 13, 13)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Conthieu, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Nguoinop, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Danop, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 5, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txt_MaHV, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tenLop2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txt_Danop, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(31, 31, 31)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tenHS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel17)
                    .addComponent(txt_Conthieu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_Nguoinop, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(txt_Giatien2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_Phainop2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15))
                            .addComponent(jDateChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_MaHV, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btn_Submit)
                .addGap(29, 29, 29))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-student-male-96.png"))); // NOI18N

        table_Data_NopTien.setBackground(new java.awt.Color(204, 153, 255));
        table_Data_NopTien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table_Data_NopTien);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)
                        .addGap(10, 10, 10)))
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tab_thu.addTab("Nộp tiền", jPanel1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1177, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tab_thu, javax.swing.GroupLayout.DEFAULT_SIZE, 1177, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tab_thu, javax.swing.GroupLayout.PREFERRED_SIZE, 439, Short.MAX_VALUE))
        );

        tab_thu.getAccessibleContext().setAccessibleName("Thống kê");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tab_thuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_thuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tab_thuMouseClicked

    private void btn_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HomeActionPerformed
        // TODO add your handling code here:
        HomeView home = new HomeView();
        home.setVisible(true);
        home.setResizable(false);
        home.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btn_HomeActionPerformed

    private void btn_searchClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchClassActionPerformed
        lopHocController = new LopHocController();
        hocSinhController = new HocSinhController();
        hocPhiController = new HocPhiController();
        List<HocSinh> hocsinhList = new ArrayList<>();
        List<LopHoc> lophocList = new ArrayList<>();

        String TenLop = txt_search.getText();
        if (TenLop.equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền tên của một lớp học ", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            defaultTableModel = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            table_Data_HocPhiByLop1.setModel(defaultTableModel);
            defaultTableModel.addColumn("STT");
            defaultTableModel.addColumn("Mã lớp");
            defaultTableModel.addColumn("Tên lớp");
            defaultTableModel.addColumn("Sĩ số");
            defaultTableModel.addColumn("Thời lượng");
            defaultTableModel.addColumn("Giá tiền");
            defaultTableModel.addColumn("Phải nộp");

            lophocList = hocPhiController.getListClassByName(TenLop.trim());
            if (lophocList.size() == 0) {
                JOptionPane.showMessageDialog(this, "Không tồn tại lớp học !", "Lỗi", JOptionPane.ERROR_MESSAGE);

            } else {
                int i = 1;
                for (LopHoc lopHoc : lophocList) {
                    defaultTableModel.addRow(new Object[]{i++, lopHoc.getMaLop(), lopHoc.getTenLop(), lopHoc.getSiSo(), lopHoc.getThoiLuong()+" buổi",
                        lopHoc.getGiatien(), lopHoc.getPhainop()});
                }
                table_Data_HocPhiByLop1.setComponentPopupMenu(PopupMenu2);
            }

        }


    }//GEN-LAST:event_btn_searchClassActionPerformed

    private void btn_searchHSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchHSActionPerformed
        // TODO add your handling code here:
        List<HocSinh> hocsinhList = new ArrayList<>();
        hocPhiController = new HocPhiController();

        String TenHV = txt_search1.getText();
        if (TenHV.equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền tên của một học sinh ", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            defaultTableModel = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            table_Data_NopTien.setModel(defaultTableModel);
            defaultTableModel.addColumn("STT");
            defaultTableModel.addColumn("Mã HV");
            defaultTableModel.addColumn("Họ tên");
            defaultTableModel.addColumn("Tên lớp");

            hocsinhList = hocPhiController.getListStudentByName(TenHV.trim());
            if (hocsinhList.size() == 0) {
                JOptionPane.showMessageDialog(this, "Không tồn tại học sinh !", "Lỗi", JOptionPane.ERROR_MESSAGE);

            } else {
                int i = 1;
                for (HocSinh hocsinh : hocsinhList) {
                    defaultTableModel.addRow(new Object[]{i++, hocsinh.getMaHV(), hocsinh.getHoTen(), hocsinh.getTenLop()});
                }
                table_Data_NopTien.setComponentPopupMenu(PopupMenu);
            }
        }
    }//GEN-LAST:event_btn_searchHSActionPerformed

    private void txt_NguoinopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NguoinopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NguoinopActionPerformed

    private void btn_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SubmitActionPerformed
        // TODO add your handling code here:
        HocPhi hocphi = new HocPhi();
        hocPhiController = new HocPhiController();
        hocSinhController = new HocSinhController();
        hocphi.setMaHV(txt_MaHV.getText());
        hocphi.setMaLop(hocSinhController.getMaLopByMaHV(txt_MaHV.getText()).getMaLop());

        if (validForm()) {
            hocphi.setDanop(Integer.parseInt(txt_Danop.getText()));
            hocphi.setConthieu(Integer.parseInt(txt_Phainop2.getText()) - Integer.parseInt(txt_Danop.getText()));
            txt_Conthieu.setText(String.valueOf(hocphi.getConthieu()));
            hocphi.setNgaynop(jDateChooser.getDate());
            if (jDateChooser.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Ngày nộp không được trống");
            } else {
                hocphi.setNguoinop(txt_Nguoinop.getText());
                
                int check = hocPhiController.Update(hocphi);
                if (check == 1) {
                    JOptionPane.showMessageDialog(this, "Sửa học phí thành công");
                } else {
                    hocPhiController.Add(hocphi);
                    JOptionPane.showMessageDialog(this, "Nộp học phí thành công");
                    
                }
            }

        } else {
            return;
        }
    }//GEN-LAST:event_btn_SubmitActionPerformed

    private void HienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HienThiActionPerformed
        // TODO add your handling code here:
        int row = table_Data_NopTien.getSelectedRow();
        if (row != -1) {
            HocPhi hp = new HocPhi();
            List<HocPhi> ListHocPhi = new ArrayList<>();

            hocPhiController = new HocPhiController();
            lopHocController = new LopHocController();
            String MaHV = String.valueOf(table_Data_NopTien.getValueAt(row, 1));
            String TenHV = String.valueOf(table_Data_NopTien.getValueAt(row, 2));
            String TenLop = String.valueOf(table_Data_NopTien.getValueAt(row, 3));

            lop = lopHocController.getClassByName(TenLop);
            hp = hocPhiController.getStudentByName(TenHV);
            ListHocPhi = hocPhiController.getHocPhiByMaHV(MaHV);

            txt_MaHV.setText(MaHV);
            txt_tenHS.setText(TenHV);
            txt_tenLop2.setText(TenLop);
            txt_Giatien2.setText(String.valueOf(lop.getGiatien()));
            txt_Phainop2.setText(String.valueOf(lop.getPhainop()));
            
            if (ListHocPhi.size() == 0) {
                txt_Danop.setText("");
                txt_Conthieu.setText("");
                jDateChooser.setDate(null);
                txt_Nguoinop.setText("");
            } else {
                txt_Danop.setText(String.valueOf(hp.getDanop()));
                txt_Conthieu.setText(String.valueOf(hp.getPhainop() - hp.getDanop()));
                jDateChooser.setDate(hp.getNgaynop());
                txt_Nguoinop.setText(hp.getNguoinop());
            }

        } else {
            JOptionPane.showMessageDialog(this, "Chưa chọn học sinh!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_HienThiActionPerformed

    private void ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowActionPerformed
        // TODO add your handling code here:
        int row = table_Data_HocPhiByLop1.getSelectedRow();
        if (row != -1) {
            HocPhi hp = new HocPhi();
            List<HocPhi> ListHocPhi = new ArrayList<>();

            hocPhiController = new HocPhiController();
            lopHocController = new LopHocController();
            String MaLop = String.valueOf(table_Data_HocPhiByLop1.getValueAt(row, 1));
            ListHocPhi = hocPhiController.getListStudentByMaLop(MaLop.trim());
            defaultTableModel = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            table_Data_HocSinh_Lop.setModel(defaultTableModel);
            defaultTableModel.addColumn("STT");
            defaultTableModel.addColumn("Họ tên");
            defaultTableModel.addColumn("Đã nộp");
            defaultTableModel.addColumn("Còn thiếu");
            defaultTableModel.addColumn("Người nộp");
            defaultTableModel.addColumn("Ngày nộp");

            if (ListHocPhi.size() == 0) {
                JOptionPane.showMessageDialog(this, "Lớp học chưa có học sinh !", "Lỗi", JOptionPane.ERROR_MESSAGE);

            } else {
                int i = 1;
                for (HocPhi hocPhi : ListHocPhi) {
                    defaultTableModel.addRow(new Object[]{i++, hocPhi.getHoTen(),
                        hocPhi.getDanop(), hocPhi.getPhainop() - hocPhi.getDanop(), hocPhi.getNguoinop(), hocPhi.getNgaynop()});
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Chưa chọn lớp học!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ShowActionPerformed
    private boolean validForm() {
        if (!Validation.isEmpty(txt_Danop, "Số tiền đã nộp không được trống!")) {
            return false;
        }
        if (!Validation.isNumber(txt_Danop, "Số tiền đã nộp phải là số!")) {
            return false;
        }
        if (!Validation.checkGiaTien(txt_Danop, "Số tiền đã nộp phải >= 1.000 VNĐ!")) {
            return false;
        }       
        if (!Validation.isEmpty(txt_Nguoinop, "Người nộp không được trống!")) {
            return false;
        }
        if (!Validation.isEmptyDate(jDateChooser, "Ngày nộp không được trống!")) {
            return false;
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem HienThi;
    private javax.swing.JPopupMenu PopupMenu;
    private javax.swing.JPopupMenu PopupMenu2;
    private javax.swing.JMenuItem Show;
    private javax.swing.JButton btn_Home;
    private javax.swing.JButton btn_Submit;
    private javax.swing.JButton btn_searchClass;
    private javax.swing.JButton btn_searchHS;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane tab_thu;
    private javax.swing.JTable table_Data_HocPhiByLop1;
    private javax.swing.JTable table_Data_HocSinh_Lop;
    private javax.swing.JTable table_Data_NopTien;
    private javax.swing.JTextField txt_Conthieu;
    private javax.swing.JTextField txt_Danop;
    private javax.swing.JTextField txt_Giatien2;
    private javax.swing.JTextField txt_MaHV;
    private javax.swing.JTextField txt_Nguoinop;
    private javax.swing.JTextField txt_Phainop2;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_search1;
    private javax.swing.JTextField txt_tenHS;
    private javax.swing.JTextField txt_tenLop2;
    // End of variables declaration//GEN-END:variables
}
