/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.LopHocController;
import Controller.HocPhiController;
import Controller.HocSinhController;
import Model.HocSinh;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import Model.LopHoc;
import Utils.Validation;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.HorizontalAlignment;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFCellStyle;
import org.apache.poi.xssf.usermodel.XSSFCreationHelper;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Administrator
 */
public class QLLopHocView extends javax.swing.JFrame {

    Controller.LopHocController lopHocController;
    Controller.HocPhiController hocPhiController;
    Controller.HocSinhController hocSinhController;
    DefaultTableModel defaultTableModel;

    /**
     * Creates new form QLLopHocView
     */
    public QLLopHocView() {
        initComponents();

        ImageIcon image = new ImageIcon("C:\\Users\\Administrator\\Documents\\NetBeansProjects\\DemoBTL - Copy2\\src\\img\\logo.png");
        this.setIconImage(image.getImage());

        lopHocController = new LopHocController();
        hocPhiController = new HocPhiController();
        defaultTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        table_Data_LH.setModel(defaultTableModel);
        defaultTableModel.addColumn("Mã lớp ");
        defaultTableModel.addColumn("Tên lớp");
        defaultTableModel.addColumn("Sĩ số");
        defaultTableModel.addColumn("Thời lượng");
        defaultTableModel.addColumn("Giá tiền");
        defaultTableModel.addColumn("Phải nộp");

        setTableData(lopHocController.getAllLopHocs());
    }

    public void setTableData(List<LopHoc> lopHoc) {
        for (LopHoc lopHoc1 : lopHoc) {
            defaultTableModel.addRow(new Object[]{lopHoc1.getMaLop(), lopHoc1.getTenLop(), lopHoc1.getSiSo(),
                lopHoc1.getThoiLuong()+" buổi", lopHoc1.getGiatien(), lopHoc1.getPhainop()});
        }
    }

    private boolean validForm() {
        if (!Validation.isEmpty(txt_maLop, "Mã lớp không được trống!")) {
            return false;
        }
        if (!Validation.isEmpty(txt_tenLop, "Tên lớp không được trống!")) {
            return false;
        }
        if (!Validation.isEmpty(txt_thoiLuong, "Thời lượng không được trống!")) {
            return false;
        }
        if (!Validation.isNumber(txt_thoiLuong, "Thời lượng phải là số!")) {
            return false;
        }
        if (!Validation.isEmpty(txt_giaTien, "Giá tiền không được trống!")) {
            return false;
        }
        if (!Validation.isNumber(txt_giaTien, "Giá tiền phải là số!")) {
            return false;
        }
        if (!Validation.checkGiaTien(txt_giaTien, "Giá tiền phải là số và >= 1.000 VNĐ!")) {
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_Home = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_maLop = new javax.swing.JTextField();
        txt_tenLop = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_thoiLuong = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_giaTien = new javax.swing.JTextField();
        btn_Xoa = new javax.swing.JButton();
        btn_Refresh = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        btn_Show = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_Them = new javax.swing.JButton();
        btn_XuatExcel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Data_LH = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-studying-96.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1161, 509));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel9.setText("QUẢN LÝ LỚP HỌC ");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-sakura-48.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setText("Trường THCS Chuyên Phan Bội Châu______________ ");

        btn_Home.setBackground(new java.awt.Color(153, 153, 255));
        btn_Home.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-home-32.png"))); // NOI18N
        btn_Home.setMaximumSize(new java.awt.Dimension(89, 39));
        btn_Home.setMinimumSize(new java.awt.Dimension(89, 39));
        btn_Home.setPreferredSize(new java.awt.Dimension(89, 39));
        btn_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(22, 22, 22)
                .addComponent(jLabel10)
                .addGap(118, 118, 118)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(63, 63, 63))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btn_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jPanel4.setBackground(new java.awt.Color(204, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "THÔNG TIN LỚP HỌC ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Mã lớp");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Tên lớp");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Thời lượng");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Giá tiền ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_maLop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tenLop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_thoiLuong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_giaTien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(107, 107, 107))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_maLop, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_tenLop, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_thoiLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_giaTien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(62, 62, 62))
        );

        btn_Xoa.setBackground(new java.awt.Color(255, 102, 102));
        btn_Xoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-delete-30.png"))); // NOI18N
        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_Refresh.setBackground(new java.awt.Color(102, 255, 204));
        btn_Refresh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-refresh-30.png"))); // NOI18N
        btn_Refresh.setText("Refresh");
        btn_Refresh.setMaximumSize(new java.awt.Dimension(103, 39));
        btn_Refresh.setMinimumSize(new java.awt.Dimension(103, 39));
        btn_Refresh.setPreferredSize(new java.awt.Dimension(103, 39));
        btn_Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RefreshActionPerformed(evt);
            }
        });

        btn_Sua.setBackground(new java.awt.Color(102, 255, 204));
        btn_Sua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-edit-30.png"))); // NOI18N
        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        btn_Show.setBackground(new java.awt.Color(102, 255, 204));
        btn_Show.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-touch-24.png"))); // NOI18N
        btn_Show.setText("Hiển thị");
        btn_Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ShowActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-studying-96.png"))); // NOI18N

        btn_Them.setBackground(new java.awt.Color(102, 255, 204));
        btn_Them.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-add-30.png"))); // NOI18N
        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_XuatExcel.setBackground(new java.awt.Color(153, 255, 153));
        btn_XuatExcel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_XuatExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-microsoft-excel-48.png"))); // NOI18N
        btn_XuatExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XuatExcelActionPerformed(evt);
            }
        });

        table_Data_LH.setBackground(new java.awt.Color(204, 153, 255));
        table_Data_LH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_Data_LH.setGridColor(new java.awt.Color(153, 153, 255));
        jScrollPane1.setViewportView(table_Data_LH);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-book-shelf-96.png"))); // NOI18N

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-book-shelf-96.png"))); // NOI18N

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-book-shelf-96.png"))); // NOI18N

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-book-shelf-96.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(btn_Them)
                        .addGap(83, 83, 83)
                        .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel25)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel26)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel27)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel28))
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_Xoa)
                        .addGap(60, 60, 60)
                        .addComponent(btn_Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(btn_Show)
                        .addGap(56, 56, 56)
                        .addComponent(btn_XuatExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(27, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26))
                                .addGap(0, 6, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_XuatExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_Them)
                                    .addComponent(btn_Sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_Refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_Xoa)
                                    .addComponent(btn_Show, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(24, 24, 24))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        LopHoc lop = new LopHoc();
        String maLop = txt_maLop.getText();
        String tenLop = txt_tenLop.getText();
        String thoiLuong = txt_thoiLuong.getText();
        String giaTien = txt_giaTien.getText();

        LopHoc check = lopHocController.getLopHocByMaLop(maLop);
        if (check != null) {
            JOptionPane.showMessageDialog(null, "Mã lớp học đã tồn tại");
            txt_maLop.setBackground(Color.yellow);
            txt_maLop.requestFocus();
        } else {
            if (validForm()) {
                lop.setMaLop(maLop);
                lop.setTenLop(tenLop);
                lop.setSiSo(0);
                lop.setThoiLuong(Integer.parseInt(thoiLuong));
                lop.setGiatien(Integer.parseInt(giaTien));
                lop.setPhainop(Integer.parseInt(thoiLuong) * Integer.parseInt(giaTien));

                lopHocController.AddClass(lop);
                JOptionPane.showMessageDialog(this, "Thêm lớp học thành công");
            } else {
                return;
            }
        }
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        // TODO add your handling code here:
        int row = table_Data_LH.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một lớp học ", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            String MaLop = String.valueOf(table_Data_LH.getValueAt(row, 0));
            SuaLopHocView edit = new SuaLopHocView(MaLop);
            edit.setVisible(true);
            edit.setResizable(false);
            edit.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:
        List<HocSinh> listHS = new ArrayList<>();
        hocSinhController = new HocSinhController();
        int row = table_Data_LH.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một lớp học ", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            int confirm = JOptionPane.showConfirmDialog(QLLopHocView.this, "Bạn có chắc chắn xóa không?");
            if (confirm == JOptionPane.YES_OPTION) {
                String MaLop = String.valueOf(table_Data_LH.getValueAt(row, 0));
                lopHocController.Delete(MaLop);
                HocSinh hs = new HocSinh();
                List<HocSinh> ListHS = new ArrayList<>();
                ListHS = hocSinhController.getHocSinhByMaLop(MaLop);
                for (int i = 0; i < ListHS.size(); i++) {
                    hs = hocSinhController.getMaHVbyMaLop(MaLop);
                    String MaHV = hs.getMaHV();
                    hocSinhController.Delete(MaHV);
                }
                    defaultTableModel.setRowCount(0);
                    setTableData(lopHocController.getAllLopHocs());
                    JOptionPane.showMessageDialog(this, "Xóa lớp học thành công!");
                }else{
                JOptionPane.showMessageDialog(this, "Xóa lớp học thất bại!");
            }
            }

    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RefreshActionPerformed
        // TODO add your handling code here:
        defaultTableModel.setRowCount(0);
        setTableData(lopHocController.getAllLopHocs());
    }//GEN-LAST:event_btn_RefreshActionPerformed

    private void btn_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HomeActionPerformed
        // TODO add your handling code here:
        HomeView home = new HomeView();
        home.setVisible(true);
        home.setResizable(false);
        home.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btn_HomeActionPerformed

    private void btn_ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ShowActionPerformed
        // TODO add your handling code here:
        int row = table_Data_LH.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một lớp học ", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            String MaLop = String.valueOf(table_Data_LH.getValueAt(row, 0));
            HienThiLopView show = new HienThiLopView(MaLop);
            show.setVisible(true);
            show.setResizable(false);
            show.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_btn_ShowActionPerformed

    private void btn_XuatExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XuatExcelActionPerformed
        // TODO add your handling code here:
        hocSinhController = new HocSinhController();
        lopHocController = new LopHocController();
        try {
            hocSinhController = new HocSinhController();
            XSSFWorkbook workbook = new XSSFWorkbook();
            XSSFSheet sheet = workbook.createSheet("Danh sách lớp");

            XSSFCreationHelper createHelper = workbook.getCreationHelper();
            XSSFCellStyle cellStyle = workbook.createCellStyle();
            cellStyle.setDataFormat(createHelper.createDataFormat().getFormat("dd-MM-yyyy"));

            XSSFRow row = null;
            Cell cell = null;
            sheet.setColumnWidth(2, 6000);
            sheet.setColumnWidth(4, 3500);
            sheet.setColumnWidth(5, 3500);
            sheet.setColumnWidth(6, 6000);
            sheet.setColumnWidth(7, 6000);

            row = sheet.createRow((short) 0);
            row.setHeight((short) 500);
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("DANH SÁCH LỚP");

            row = sheet.createRow((short) 2);
            row.setHeight((short) 500);
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("STT");
            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("Mã HV");
            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("Họ và Tên");
            cell = row.createCell(3, CellType.STRING);
            cell.setCellValue("Giới Tính");
            cell = row.createCell(4, CellType.STRING);
            cell.setCellValue("Ngày Sinh");
            cell = row.createCell(5, CellType.STRING);
            cell.setCellValue("Sđt Phụ Huynh");
            cell = row.createCell(6, CellType.STRING);
            cell.setCellValue("Tên Phụ Huynh");
            cell = row.createCell(7, CellType.STRING);
            cell.setCellValue("Địa Chỉ");
            int row1 = table_Data_LH.getSelectedRow();
            if (row1 == -1) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn một lớp học ", "Lỗi", JOptionPane.ERROR_MESSAGE);
            } else {

                String MaLop = String.valueOf(table_Data_LH.getValueAt(row1, 0));
                List<HocSinh> hocsinh = hocSinhController.getHocSinhByMaLop(MaLop);
                if (hocsinh.size() == 0) {
                    JOptionPane.showMessageDialog(this, "Lớp học chưa có học sinh. Hãy thêm học sinh để xuất excel", "Lỗi", JOptionPane.ERROR_MESSAGE);
                } else {
                    for (int i = 0; i < hocsinh.size(); i++) {
                        HocSinh hs = hocsinh.get(i);
                        row = sheet.createRow((short) 3 + i);
                        row.setHeight((short) 400);
                        row.createCell(0).setCellValue(i + 1);
                        row.createCell(1).setCellValue(hs.getMaHV());
                        row.createCell(2).setCellValue(hs.getHoTen());
                        row.createCell(3).setCellValue(hs.getGioiTinh());
                        Cell dateOfBirth = row.createCell(4);
                        dateOfBirth.setCellValue(hs.getNgaySinh());
                        dateOfBirth.setCellStyle(cellStyle);
                        row.createCell(5).setCellValue(hs.getSdtPH());
                        row.createCell(6).setCellValue(hs.getTenPH());
                        row.createCell(7).setCellValue(hs.getDiaChi());
                    }

                    FileOutputStream fileOut = new FileOutputStream(new File("D:\\Danh sach lop " + MaLop + ".xlsx"));
                    workbook.write(fileOut);
                    fileOut.close();
                    JOptionPane.showMessageDialog(this, "Xuất excel lớp " + MaLop + " thành công");
                }

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_XuatExcelActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Home;
    private javax.swing.JButton btn_Refresh;
    private javax.swing.JButton btn_Show;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JButton btn_XuatExcel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_Data_LH;
    private javax.swing.JTextField txt_giaTien;
    private javax.swing.JTextField txt_maLop;
    private javax.swing.JTextField txt_tenLop;
    private javax.swing.JTextField txt_thoiLuong;
    // End of variables declaration//GEN-END:variables
}
